#ifndef _TREE_DWELLER_FLAGS_H_
#define _TREE_DWELLER_FLAGS_H_
enum TreeDweellerFlags	//Change em for each project ?
{
	TDF_DEFAULT = 1,
	TDF_LIGHT = 2,
	TDF_INSTANCE = 4,
	TDF_FRUSTUM = 8,
	TDF_CUSTOM_INSTANCE = 16,
	TDF_TERRAIN_INSTANCE = 32,
	TDF_EMITTER = 64,
	TDF_TINTED = 128,
	TDF_ALL = TDF_DEFAULT | TDF_LIGHT | TDF_INSTANCE | TDF_FRUSTUM | TDF_CUSTOM_INSTANCE | TDF_TERRAIN_INSTANCE | TDF_EMITTER | TDF_TINTED,

};
#endif